# Generated by Django 5.0.3 on 2024-03-27 11:40

import django.db.models.deletion
import information.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_active',
            field=models.BooleanField(default=False, verbose_name='Bil ej aktiv'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=100, verbose_name='Bil namn'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_regnr',
            field=models.CharField(max_length=50, unique=True, verbose_name='Reg Nr'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.cartype', verbose_name='Bil typ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.unit', verbose_name='Enhet'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='car_type_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Fordonstyp'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_cubic',
            field=models.IntegerField(blank=True, default=0, validators=[information.models.validate_positive_or_zero], verbose_name='Kubik'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_for',
            field=models.CharField(max_length=200, verbose_name='Ställning för'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_location',
            field=models.CharField(max_length=200, verbose_name='Plats'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_marking',
            field=models.CharField(blank=True, max_length=200, verbose_name='Märkning'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_material',
            field=models.BooleanField(default=False, verbose_name='Ställnings material'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_number',
            field=models.IntegerField(verbose_name='Ställnings nummer'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_po',
            field=models.CharField(blank=True, max_length=200, verbose_name='Inköpsordernummer'),
        ),
        migrations.AlterField(
            model_name='scaffold',
            name='scaffold_stair',
            field=models.IntegerField(blank=True, default=0, validators=[information.models.validate_positive_or_zero], verbose_name='Trappmeter'),
        ),
    ]
