# Generated by Django 5.0.3 on 2024-03-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_car_car_active_alter_car_car_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_active',
            field=models.BooleanField(default=True, verbose_name='Bil ej aktiv'),
        ),
    ]
