# Generated by Django 5.0.3 on 2024-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_car_car_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_active',
            field=models.BooleanField(default=True, verbose_name='Bil aktiv'),
        ),
    ]
